! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! The Reaction Rates File
!
! Generated by KPP-2.2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!
! File                 : gckpp_adj_Rates.f90
! Time                 : Tue May 14 19:43:54 2013
! Working directory    : /home/daven/kpp-2.2.1/GC_KPP
! Equation file        : gckpp_adj.kpp
! Output root filename : gckpp_adj
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_adj_Rates

  USE gckpp_adj_Parameters
  USE gckpp_adj_Global
  IMPLICIT NONE

CONTAINS

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Update_RCONST - function to update rate constants
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )

  USE COMODE_MOD,        ONLY : R_KPP
  USE gckpp_adj_Monitor

  INTEGER :: N

  DO N = 1, NREACT
     RCONST(N) = R_KPP(JLOOP,IND(N))
  ENDDO

  !KLUDGE FIX for isoprene nitrate bug in globchem.dat: deactivate
  ! RIO2 + NO --> HNO3
  ! (fp, dkh, 05/10/13)
  ! Also, modify globchem.eqn to include 0.1 HNO3 from the
  ! other  RIO2 + NO, RCONST(55)
  RCONST(56) = 0d0

END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


END MODULE gckpp_adj_Rates

